//
// Created by Callie on 2019/2/20.
//

#ifndef PROJ_ANDROID_UNITYMONETIZATIONJNI_H
#define PROJ_ANDROID_UNITYMONETIZATIONJNI_H


class UnityMonetizationJNI {

};


#endif //PROJ_ANDROID_UNITYMONETIZATIONJNI_H
